package com.rosan.installer.ui.page.main.settings.preferred.subpage.about

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.add
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.twotone.ArrowBack
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.ExperimentalMaterial3ExpressiveApi
import androidx.compose.material3.LargeFlexibleTopAppBar
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedCard
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.material3.contentColorFor
import androidx.compose.material3.rememberTopAppBarState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.input.nestedscroll.nestedScroll
import androidx.compose.ui.platform.LocalUriHandler
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.DialogProperties
import androidx.navigation.NavController
import com.mikepenz.aboutlibraries.entity.Library
import com.mikepenz.aboutlibraries.ui.compose.LibraryDefaults
import com.mikepenz.aboutlibraries.ui.compose.android.produceLibraries
import com.mikepenz.aboutlibraries.ui.compose.m3.LibrariesContainer
import com.mikepenz.aboutlibraries.ui.compose.m3.chipColors
import com.mikepenz.aboutlibraries.ui.compose.m3.libraryColors
import com.rosan.installer.R
import com.rosan.installer.ui.icons.AppIcons
import com.rosan.installer.ui.page.main.widget.card.InfoTipCard
import com.rosan.installer.ui.page.main.widget.setting.AppBackButton
import com.rosan.installer.ui.theme.getM3TopBarColor
import com.rosan.installer.ui.theme.installerHazeEffect
import com.rosan.installer.ui.theme.rememberMaterial3HazeStyle
import dev.chrisbanes.haze.HazeState
import dev.chrisbanes.haze.hazeSource

@OptIn(ExperimentalMaterial3Api::class, ExperimentalMaterial3ExpressiveApi::class)
@Composable
fun OpenSourceLicensePage(
    navController: NavController,
    isM3E: Boolean,
    useBlur: Boolean,
) {
    val topAppBarState = rememberTopAppBarState()
    val hazeState = if (useBlur) remember { HazeState() } else null
    val hazeStyle = rememberMaterial3HazeStyle()
    val scrollBehavior = TopAppBarDefaults.exitUntilCollapsedScrollBehavior(topAppBarState)

    // from https://github.com/mikepenz/AboutLibraries#setup
    // Android: Provide resource identifier for the `R.raw.aboutlibraries` file.
    // This file is generated by the AboutLibraries Gradle plugin.
    val libraries by produceLibraries(R.raw.aboutlibraries)

    var selectedLibrary by remember { mutableStateOf<Library?>(null) }

    Scaffold(
        modifier = Modifier
            .fillMaxSize()
            .nestedScroll(scrollBehavior.nestedScrollConnection),
        containerColor = MaterialTheme.colorScheme.surfaceContainer,
        topBar = {
            if (isM3E) {
                LargeFlexibleTopAppBar(
                    modifier = Modifier.installerHazeEffect(hazeState, hazeStyle),
                    windowInsets = TopAppBarDefaults.windowInsets.add(WindowInsets(left = 12.dp)),
                    title = { Text(text = stringResource(id = R.string.open_source_license)) },
                    scrollBehavior = scrollBehavior,
                    navigationIcon = {
                        Row {
                            AppBackButton(
                                onClick = { navController.navigateUp() },
                                icon = Icons.AutoMirrored.TwoTone.ArrowBack,
                                modifier = Modifier.size(36.dp),
                                containerColor = MaterialTheme.colorScheme.onSurfaceVariant.copy(
                                    alpha = 0.1f
                                )
                            )
                            Spacer(modifier = Modifier.size(16.dp))
                        }
                    },
                    colors = TopAppBarDefaults.topAppBarColors(
                        containerColor = hazeState.getM3TopBarColor(),
                        titleContentColor = MaterialTheme.colorScheme.onBackground,
                        scrolledContainerColor = hazeState.getM3TopBarColor()
                    )
                )
            } else {
                TopAppBar(
                    title = {
                        Text(text = stringResource(id = R.string.open_source_license))
                    },
                    scrollBehavior = scrollBehavior,
                    navigationIcon = { AppBackButton(onClick = { navController.navigateUp() }) }
                )
            }
        },
    ) { paddingValues ->
        val cornerRadius = 16.dp
        LibrariesContainer(
            libraries = libraries,
            libraryModifier = Modifier
                .padding(vertical = 4.dp)
                .clip(RoundedCornerShape(cornerRadius)),
            modifier = Modifier
                .fillMaxSize()
                .padding(horizontal = 16.dp)
                .then(hazeState?.let { Modifier.hazeSource(it) } ?: Modifier),
            contentPadding = paddingValues,// PaddingValues(horizontal = 16.dp),
            colors = LibraryDefaults.libraryColors(
                libraryBackgroundColor = MaterialTheme.colorScheme.surfaceBright,
                libraryContentColor = MaterialTheme.colorScheme.onSurface,
                // To maintain the original appearance, explicitly set the license chip colors
                // to match the old function's default badge colors.
                licenseChipColors = LibraryDefaults.chipColors(
                    containerColor = MaterialTheme.colorScheme.primary,
                    contentColor = contentColorFor(MaterialTheme.colorScheme.primary)
                )
            ),
            onLibraryClick = { library ->
                selectedLibrary = library
            }
        )

        if (selectedLibrary != null) {
            val library = selectedLibrary!!
            val uriHandler = LocalUriHandler.current
            AlertDialog(
                onDismissRequest = { selectedLibrary = null },
                confirmButton = {
                    Button(onClick = { selectedLibrary = null }) {
                        Text(stringResource(R.string.close))
                    }
                },
                dismissButton = {
                    library.website.let { url ->
                        OutlinedButton(onClick = {
                            uriHandler.openUri(url!!)
                        }) {
                            Text(stringResource(R.string.visit_home_page))
                        }
                    }
                },
                title = {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth(),
                        horizontalArrangement = Arrangement.Center
                    ) {
                        Text(
                            text = library.name,
                            style = MaterialTheme.typography.headlineSmall
                        )
                    }
                },
                text = {
                    LazyColumn(
                        modifier = Modifier.fillMaxWidth(),
                        verticalArrangement = Arrangement.spacedBy(12.dp)
                    ) {
                        item {
                            InfoTipCard(
                                icon = AppIcons.License,
                                text = stringResource(R.string.license, library.licenses.joinToString(separator = ", ") { it.name }),
                                modifier = Modifier.fillMaxWidth(),
                                noPadding = true
                            )
                        }

                        items(library.licenses.toList()) { license ->
                            OutlinedCard(
                                modifier = Modifier.fillMaxWidth(),
                                shape = RoundedCornerShape(16.dp),
                                colors = CardDefaults.outlinedCardColors(
                                    containerColor = MaterialTheme.colorScheme.surfaceContainerHighest
                                )
                            ) {
                                Column(
                                    modifier = Modifier.padding(16.dp)
                                ) {
                                    Row {
                                        Text(
                                            text = license.name,
                                            style = MaterialTheme.typography.titleMedium,
                                            color = MaterialTheme.colorScheme.primary,
                                            modifier = Modifier
                                                .clip(RoundedCornerShape(8.dp))
                                                .clickable {
                                                    license.url?.let { url ->
                                                        uriHandler.openUri(url)
                                                    }
                                                }
                                        )
                                    }

                                    Spacer(modifier = Modifier.size(8.dp))

                                    Text(
                                        text = license.licenseContent ?: stringResource(R.string.no_license_text),
                                        style = MaterialTheme.typography.bodySmall,
                                        color = MaterialTheme.colorScheme.onSurfaceVariant
                                    )
                                }
                            }
                        }
                    }
                },
                properties = DialogProperties(usePlatformDefaultWidth = false),
                modifier = Modifier.padding(24.dp)
            )
        }
    }
}